### ISSUE TITLE
linelint does not know how to handle symbolic links

### ISSUE THREAD

**Issue by sjknox13** [fernandrone/linelint#14]
When line lint is running, it fails over a symbolic link because it cannot open the file:
[EOF Rule] Ignoring file "vor/playpens/cibc/src/docs/env_info/cibc_dev.md": in rule ignore path
[EOF Rule] Ignoring file "vor/playpens/cibc/src/docs/env_info/cibc_prod.md": in rule ignore path
[EOF Rule] Ignoring file "vor/playpens/cibc/src/docs/env_info/cibc_sit.md": in rule ignore path
[EOF Rule] Ignoring file "vor/playpens/cibc/src/docs/env_info/cibc_uat.md": in rule ignore path
[EOF Rule] Ignoring file "vor/playpens/cibc/src/docs/index.md": in rule ignore path
Error opening file "vor/playpens/cibc/src/docs/user_guide": open vor/playpens/cibc/src/docs/user_guide: no such file or directory
Total of 1 file errors!

We also tried running it with ignore specified in .linelint.yml on the parent folder which resulted in the same error even if it ignored everything in the folder.

**Comment by fernandrone** [comment]
First of all, sorry for the delay. I had not been actively maintaining this repository this and ended up missing the notification.

So, interesting issue. A few comments/questions:

1. To be clear, this just happens when the symbolic link is broken -- it points to an inexistent or possibly a file that the user can't access, right? I tried with a valid symbolic link and it worked just fine. But then I created a symbolic link pointing to a path that didn't exist and I got "no such file or directory".

2. Not sure if I understood your final comment correctly but I was able to ignore the symbolic link. For example:

   ```
   $ ln -s /tmp/invalid invalid.link # create an invalid symbolic link
   $ linelint .
   Error opening file "invalid.link": open invalid.link: no such file or directory
   ```
   
   However if I add `- invalid.link` to the `ignore:` list on the config file, the link is properly ignored and I get no errors.

   Is this your behavior too?

**Comment by sjknox13** [comment]
Hey! 

Thanks for getting back to me. After looking over your notes, I gave it another go. I was able to get the github action to run successfully with the symbolic link ignored properly. I'm not exactly sure what I was doing wrong before.

Appreciate the help.
