### ISSUE TITLE
GitHub action failing to build docker image

### ISSUE THREAD

**Issue by lmasaya** [fernandrone/linelint#7]
We are using this GitHub action to doing checks, but we run across the following issue when running the action:
```Step 5/12 : RUN go mod download
   ---> Running in 3946f63452e5
  runtime: mlock of signal stack failed: 12
  runtime: increase the mlock limit (ulimit -l) or
  runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
  fatal error: mlock failed
```

This happens sometimes, but not always. This causes our Pull Requests to be unable to be merged.

**Comment by fernandrone** [comment]
Hi, sorry for this, I missed the notification for this issue.

It seems that GitHub Actions `ubuntu-latest` already has an updated Kernel https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md (Linux kernel version: 5.8.0-1036-azure), so this error shouldn't happen anymore. This comment seems to confirm that the problem is indeed at the kernel: https://github.com/golang/go/issues/37436#issuecomment-591327351

Can you confirm if this has been fixed or is still happening @lmasaya?

**Comment by lmasaya** [comment]
Yes, this is no longer occurring. Thanks for your response
